site_name: "Electromagnetic Geophysics Lab"
site_description: "Geophysical research powered by open-source software"
brand: "images/emgeolab-banner.svg"
favicon: "images/favicon.png"
thumbnail: "images/thumbnail.jpg"
url: "https://www.emgeolab.org"
domain: emgeolab.org
repository: emgeolab/website
repository_branch: main
author: Seogi Kang
twitter: sgkang09
github: emgeolab
linkedin: seogi-kang
researchgate: https://www.researchgate.net/profile/Seogi-Kang-2
location:
  department: Department of Earth Sciences
  school: Clayton H. Riddell Faculty of Environment, Earth, and Resources
  university: University of Manitoba
  country: Canada
language: en
keywords: 'geoscience, electromagnetics, geophysics, open-science, groundwater, minerals'
navigation:
  # - name: Home
  #   id: index
  - name: News
    id: news/index
  - name: Team
    id: team/index
  - name: Research
    id: research/index
  # - name: Manual
  #   id: manual/index
  - name: Opportunities
    id: opportunities/index

ignore:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md
  - environment.yml
  - Makefile
  - css/academicons/README.md
